### ISSUE TITLE
scroll in project page 

### ISSUE THREAD

**Issue by yitang** [jeromelachaud/freelancer-theme#19]
Hi,

Thanks for creating and sharing this amazing template. I'd like to use it to show my project experiences and my project summaries are bit long that doesn't fits into one page. Current version doesn't support scrolling in the project page and I wonder how could I add this functionality to it?

-Yi

**Comment by jeromelachaud** [comment]
Hi Yi,

Which browser / OS do you use?

**Comment by vitovalov** [comment]
I'd say it's not an enhancement but rather a bug. The thing is that sometimes there's no scroll in the modals. I've noticed that it happens when the window of the whole browser(e.g on 13" screen) is of lower size than the image of the post (so the image not fit and the user wants to scroll down). Then the bug is reproduced. It happened in chrome both windows and OS X.

**Comment by yitang** [comment]
@jeromelachaud @vitovalov  Thanks vitovalov, I actually can't reproduce the problem on my side and thought I made a mistake, but your comments above confirm the bug.

**Comment by jeromelachaud** [comment]
OK, it seems to be a [bug in Bootstrap] (https://github.com/twbs/bootstrap/issues/16297)
What is weird though is there ain't not such bug in the original Freelancer theme

**Comment by jeromelachaud** [comment]
fixed: https://github.com/jeromelachaud/freelancer-theme/commit/6ee599856e1749ba2e8b1d549661f1284592daa5

**Comment by yitang** [comment]
thanks.
