### ISSUE TITLE
list in post description?

### ISSUE THREAD

**Issue by fkromer** [jeromelachaud/freelancer-theme#62]
Is it possible to use lists in the post description?

- list entry 1
- list entry 2
- ...

**Comment by ConnorWalsh7** [comment]
Yes it is, you can write html in the description. So you can either write it on the same line like `<ul><li>list entry 1</li><li>list entry 2</li></ul>` but that can get a bit messy. You can write a description on multiple lines as long as each new line is indented.

Alternatively, what I found was easier (because I had this same question) is to just write the actual description of my projects in regular markdown language under the Front Matter, and in the modal.html I used `{{post.content}}` instead of `{{post.description}}` since `{{post.content}}` is everything written below the Front Matter

**Comment by fkromer** [comment]
@ConnorWalsh7 The hmtl syntax is working good enough for me (the list entries are "styled" inconsistent with the normal description entries, but I am too lazy to modify styling 😄 )
